---

- name: Run playbook-bootstrap_python3.yml
  ansible.builtin.import_playbook: playbook-bootstrap_python3.yml

- name: Run playbook-install_k3s.yml
  ansible.builtin.import_playbook: playbook-install_k3s.yml

- name: Run playbook-k3s_configure_private_registries.yml
  ansible.builtin.import_playbook: playbook-k3s_configure_private_registries.yml

- name: Run playbook-mongodb_operator_installation.yml
  ansible.builtin.import_playbook: playbook-mongodb_operator_installation.yml
