---

- name: 'Install MongoDB'
  hosts: 'k3s1'
  gather_facts: true
  become: false
  module_defaults:
    kubernetes.core.helm:
      kubeconfig: './k3s-kubeconfig'
    kubernetes.core.k8s:
      kubeconfig: './k3s-kubeconfig'
    kubernetes.core.k8s_info:
      kubeconfig: './k3s-kubeconfig'

  tasks:

    - name: 'Create the mongodb namespace'
      delegate_to: 'localhost'
      kubernetes.core.k8s:
        name: 'mongodb'
        api_version: 'v1'
        kind: 'Namespace'
        state: 'present'

    - name: 'Install MongoDB via the helm chart'
      delegate_to: 'localhost'
      kubernetes.core.helm:
        chart_ref: 'oci://registry-1.docker.io/bitnamicharts/mongodb'
        release_name: 'mongodb'
        release_namespace: 'mongodb'
        release_values:
          global:
            compatibility:
              openshift:
                adaptSecurityContext: disable
          auth:
            rootPassword: totallysecure
            databases:
              - vagrant-libvirt
            usernames:
              - vagrant-libvirt
            passwords:
              - totallysecure
          architecture: standalone
          replicaCount: 1
          service:
            type: NodePort
          persistence:
            storageClass: local-path
            size: 256Mi

    - name: 'Wait until all pods in the mongodb namespace are running'
      delegate_to: localhost
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: mongodb
      register: pod_list
      until: |
        pod_list | json_query("resources[*].status.phase") | unique | sort == ["Running"]
        or
        pod_list | json_query("resources[*].status.phase") | unique | sort == ["Running", "Succeeded"]
      retries: 12
      delay: 10

    - name: 'Create the ingressrouteTCP for MongoDB'
      delegate_to: 'localhost'
      kubernetes.core.k8s:
        name: 'mongodb'
        state: 'present'
        resource_definition: |
          apiVersion: traefik.io/v1alpha1
          kind: IngressRouteTCP
          metadata:
            name: mongodb
            namespace: mongodb
          spec:
            entryPoints:
              - web
            routes:
              - match: HostSNI(`*`)
                services:
                  - name: mongodb
                    port: 27017

    - name: 'MongoDB URL'
      delegate_to: 'localhost'
      ansible.builtin.debug:
        msg: "Use mongosh to connect to the following URL: mongodb://mongodb.{{ hostvars['k3s1']['ansible_default_ipv4']['address'] }}.sslip.io:80"

    - name: 'MongoDB Credentials'
      delegate_to: 'localhost'
      ansible.builtin.debug:
        msg: "Use the following credentials: username 'root' and password 'totallysecure'"
